name: Continuous deployment
on:
  workflow_run:
    branches: [main]
    workflows: [Continuous integration]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v0

      - uses: jetli/trunk-action@v0.4.0
      - uses: jetli/wasm-bindgen-action@v0.2.0
      - uses: actions/checkout@v3

      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release

      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
